server {
	location /a {
	cgi php /i;
	cgi bla /i;
	autoindex on;
	root /e;
	max_body_size 100000;
	redirect http://s;
	}

	location /e {
	cgi php /i;
	cgi bla /i;
	autoindex on;
	root /e;
	max_body_size 100000;
	redirect http://s;
	}
}

server {
	location /a {
	cgi php /i;
	cgi bla /i;
	autoindex on;
	root /e;
	max_body_size 100000;
	redirect http://s;
	}
	
	location /e {
	cgi php /i;
	cgi bla /i;
	autoindex on;
	root /e;
	max_body_size 100000;
	redirect http://s;
	}
}

server {
	location /b {
	cgi php /i;
	cgi bla /i;
	autoindex on;
	root /e;
	max_body_size 100000;
	redirect http://s;
	}
	
	location /e {
	cgi php /i;
	cgi bla /i;
	autoindex on;
	root /e;
	max_body_size 100000;
	redirect http://s;
	}
}