server {
	listen 127.0.0.1:8080;

	location / {
		cgi php /usr/bin/php-cgi;
		cgi bla /home/user/cpp/webserv/cgi_tester;
		autoindex on;
		root /home/user/cpp/webserv/data/www;
		allowed_method GET;
	}

	location /post_body/ {
		cgi php /usr/bin/php-cgi;
		cgi bla /home/user/cpp/webserv/cgi_tester;
		root /home/user/cpp/webserv/data/www;
		autoindex on;
		max_body_size 100;
		allowed_method POST;
	}
	
	location /directory/ {
		cgi php /usr/bin/php-cgi;
		cgi bla /home/user/cpp/webserv/cgi_tester;
		root /home/user/cpp/webserv/data/www/YoupiBanane;
		allowed_method GET|POST;
		index youpi.bad_extension;
	}
}